### ISSUE TITLE
Understanding the celluloid architecture

### ISSUE THREAD

**Issue by dilumnavanjana** [dilumnavanjana/celluloid#12]
@digitalextremist here is the list of questions I have,

1 - Can you describe me the purpose of the `mailbox`? Once you told me that `mailbox` is a queue, I have seen that a new mailbox is created for every new actor. So is that `mailbox` queue for handling the actor's tasks one after another?

2 - Suppose I create 2 actors (A & B). First A & then B. If I want to add DeadlockPreventor class for this program, which will be the best place? (Because from that place I will be able to access all these Actors to check their status or what ever thing to detect deadlock, Correct me if I'm wrong)

3 - Can you describe what is Fiber? I saw in #509 they mentioned about Fiber on JRuby to detect deadlock.

4 - One thread for one Actor. Am I correct??

I tried my best to ask these questions in a meaningful way, sorry if you can't understand those. These days I'm debugging through celluloid source with `pry` gem.

**Comment by digitalextremist** [comment]
### 1

> Can you describe me the purpose of the mailbox? Once you told me that mailbox is a queue, I have seen that a new mailbox is created for every new actor. So is that mailbox queue for handling the actor's tasks one after another?

Yes. Every time you call an `Actor` method, that method call is just being put into the `@mailbox`of that `Actor` by a `*Proxy` - at the back of the queue, unless it's a `SystemEvent`, then it goes in at the front.

### 2

The place that seems to make the most sense to me is either in `ActorSystem` or `Group` ... in a way, this new class is like `StackDump` because it goes through the entire `ActorSystem`. And `StackDumper` attaches to the `ActorSystem` class.

### 3

Ruby Fibers are *like* Threads, but not Threads ( except in jRuby! )

Here, let me google that for you:

* http://ruby-doc.org/core-2.2.1/Fiber.html
* http://stackoverflow.com/questions/16658221/what-is-the-point-of-fibers-in-ruby#16658479

You are able to start/resume, pause/hold, and transfer control between individual running code blocks, *like* a Thread, without spinning up an entirely new Thread, again -- except in jRuby, where what Ruby calls a `Fiber` jRuby treats as a `Thread` ...

### 4

Yep, created by `ThreadHandle` in the `ActorSystem` by `initialize` on `Actor` ( which is why I say, attach to `ActorSystem` for doing deadlock detection.

----

By the way, I suggest you call the deadlock preventor `Unlocker` to keep it short and sweet, and focus on what the class does: because it cannot prevent deadlocks, but it can to unlock them... detect & resolve. I would even highly suggest this become `Group::Unlocker` whether it works from `ActorSystem` or not. You could easily have `Unlocker` use `.each_actor` for its work. In fact, I can make that `Group` method if you would like to use it.

**Comment by digitalextremist** [comment]
Added `#each_actor` but have not tested it: f64061378ddcd4dc638541f7034e00dfeaae9b1b
