### ISSUE TITLE
Create report on major changes in the `refactor-test-suite` branch.

### ISSUE THREAD

**Issue by digitalextremist** [dilumnavanjana/celluloid#3]
For starters:
- [ ] Outline what the main "theory" changes were.
- [ ] For each major change, explain why the new way is better.
- [ ] Determine how those `:flaky` tests can be made into consistent tests.

**Comment by dilumnavanjana** [comment]
#522 - dead checking an actor rather than checking actor is alive
#527 - Extra delay for flaky test & No more 0.9 sleep time
#534, #535 - Install Bundle before installing celluloid / remove rvm 1.9.3 manditory

Here are the changes I have noticed in ```refactor-test-suite```. I didn't list changes that were changed 6 days ago. Should I list those old changes too??

**Comment by digitalextremist** [comment]
I meant, rather than highlight the PR's, etc -- to go through the code to learn from it, because these test changes are pretty large ones. Look at the overall diff and deduce from that what changed, then describe to me what you see -- in the code itself.

**Comment by digitalextremist** [comment]
I've reviewed most of the branch so we're moving on to fixing a bug.
