### ISSUE TITLE
Add a status to actor_proxy & cell_proxy

### ISSUE THREAD

**Issue by dilumnavanjana** [dilumnavanjana/celluloid#8]
@digitalextremist While I was spending time on Celluloid, I got this simple idea of checking actors status. I just write this simple method to return the actor to check the status. I know it'll be a useless feature, but I wanted to add & test it. The implementation is on `status` branch

**Comment by digitalextremist** [comment]
What kind of status do you mean? As in, busy, idle, etc -- or what?

**Comment by dilumnavanjana** [comment]
yes I tried some status like busy, idle, running. It was just an idea came to my mind.

**Comment by digitalextremist** [comment]
What would the difference between running and busy? There is `alive?` and `dead?` already.

**Comment by dilumnavanjana** [comment]
running is something similar to running but busy means the actor is in process & main thread should not end at that moment. I faced this situation, main thread finishes while background thread is still in process

**Comment by digitalextremist** [comment]
So you mean `#status` returns a symbol of one of these: `[ :busy, :idle, :running, :dead ]`

Well there should not be a need for `:running` because if the `Actor` has a running `Task` it should be `:busy` still. From a deadlocking perspective especially. And it's important to know what the activity `:id` would be. For example if you are checking for an `Actor` not to be busy, every time you check it could still be busy and you may want to handle it as a deadlock, but maybe it got several tasks done and it's not stuck on one, so I'd say adding some kind of high-performance "identifier" would be good, to determine really where the `Actor` stands. Almost like how different commits have a unique identifier.

**Comment by digitalextremist** [comment]
It's not a bad idea. But that would be on the `ActorProxy`, checking the state of `@thread` ( which is a `ThreadHandle` ) not `@mailbox` ( which is a `Queue` ) ... We're discussing this in IRC now.
